name: mongo_dart
version: 0.7.0+1
description: MongoDB driver, implemented in pure Dart. All CRUD operations, aggregation pipeline and more!
homepage: https://github.com/mongo-dart/mongo_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bson: ^1.0.0
  crypto: ^3.0.0
  logging: ^1.0.0
  mongo_dart_query: ^1.0.0
  collection: ^1.15.0
  path: ^1.8.0
  pool: ^1.5.0
  basic_utils: ^3.0.0
  rational: ^1.0.0
  uuid: ^3.0.0
  
dev_dependencies:
  test: ^1.16.4
  pedantic: ^1.10.0