name: mongo_dart
version: 0.1.19-dev
authors:
- Vadim Tsushko <vadimtsushko@gmail.com>
- Ted Sander <ted@tedsander.com>
description: MongoDB driver for Dart
homepage: https://github.com/vadimtsushko/mongo_dart
dependencies:
  args: any
  bson: any
  logging: any
  meta: any
  mongo_dart_query: any
dev_dependencies:
  unittest: any
