name: mongo_dart
version: 0.1.33-dev
authors:
- Vadim Tsushko <vadimtsushko@gmail.com>
- Ted Sander <ted@tedsander.com>
- Paul Evans <pevans@sonardesign.com>
description: MongoDB driver for Dart
homepage: https://github.com/vadimtsushko/mongo_dart
dependencies:
  args: any
  bson: any
  crypto: any
  logging: any
  mongo_dart_query: any
dev_dependencies:
  hop: any
  unittest: any
