name: mongo_dart
version: 0.4.2
description: MongoDB driver, implemented in pure Dart. All CRUD operations, aggregation pipeline and more! 
homepage: https://github.com/mongo-dart/mongo_dart
environment:
  sdk: '>=2.5.2 <3.0.0'
dependencies:
  bson: '^0.3.2'
  crypto: '^2.1.5'
  logging: '^0.11.4'
  mongo_dart_query: '^0.4.1'
  collection: '^1.14.11'
  path: '^1.7.0'
  pool: ^1.4.0
  uuid: ^2.2.0
  basic_utils: ^2.6.2
dev_dependencies:
  test: ^1.13.0
  pedantic: ^1.9.0

